### ISSUE TITLE
[Linux] Range Error: Serving file listing from /media/DBBA-9C1E//TeslaCam/RecentClips

### ISSUE THREAD

**Issue by Haun1400** [BobStrogg/teslacam-browser#27]
Hello! I started going through the code and looking at the existing issues looking to see if anyone else is running into this issue. I'm getting the following error:

`Opening browser at http://localhost:8088
Serving file listing from /media/DBBA-9C1E//TeslaCam/RecentClips
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:270:31)
    at SendStream.send (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:670:19)
    at onstat (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:729:10)
    at FSReqWrap.oncomplete (fs.js:155:5)
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:270:31)
    at SendStream.send (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:670:19)
    at onstat (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:729:10)
    at FSReqWrap.oncomplete (fs.js:155:5)
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:270:31)
    at SendStream.send (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:670:19)
    at onstat (/opt/TeslaCam Browser/resources/app.asar/node_modules/send/index.js:729:10)
    at FSReqWrap.oncomplete (fs.js:155:5)
`

I was thinking this was most likely related to the Chrome H256 issues, however since I'm on linux I can't switch to edge or safari. That being said, I couldn't help but notice the "//" in the file path and thought that might be the issue. I can troubleshoot further as needed :)

**Comment by BobStrogg** [comment]
Thanks for looking into this!  Honestly I’ve not tested it much on Linux yet.  Do all videos fail to play?

In theory the “Browse” button in the app should still work, and then you could copy the URL into a different Linux (non-Chrome) browser?  Or is it likely H-265 isn’t supported by any Linux browser?

**Comment by Haun1400** [comment]
Anytime! I'm not familiar with Electron apps so I didn't do too much
digging. I'm also on mobile at this point in time so I'm going based on
memory. Basically the app doesn't work in any form. It tries to load the
files, but sits there "loading" in the main app panel, chrome, and Firefox.
I do seem to get a 416 error in chrome. I plan to run it on my Windows
machine just to ensure it's not something wrong with the files/usb drive.

Ran it as root and encountered the same issue.

My initial thought is the path is wrong as it has two slashes in it. I'll
see if I can make some time tomorrow to locally modify the code and run the
app, but again I'm not familiar with Electron so I might not have the
cycles tomorrow to get to it.

Thanks for the fast response, let me know if you have any other questions
that might help identify the issue!
